### ISSUE TITLE
EmailVerifier::OutOfMailServersException

### ISSUE THREAD

**Issue by luisfernandos** [kamilc/email_verifier#22]
Hi I'd like to use your gem, however I am getting the exception mentioned in the title.
Probably I am doing something wrong, but I am not able to find it.
I have put in bit at the end of application.rb

EmailVerifier.config do |config|
  config.verifier_email = "realname@realdomain.com"
end

when trying to check any email from console I receive: 
EmailVerifier::OutOfMailServersException: Unable to connect to any one of mail servers for ...

I did tried to change the config.verifier_email  to my email address, but no lucky.
I am using a MacBook Pro and 
ruby 2.0.0p481
gem 'rails', '3.2.18'

Could you help me please?

**Comment by kamilc** [comment]
@luisfernandos 

Sorry for replying so late.

I've just tried and was only able to reproduce the issue when trying on my local machine. That most probably was due to the fact that locally, I don't have a public IP. When trying from a publicly reachable server - I was able to get the library to work just fine every single time.

When you're trying to use it from an IP that a server either cannot reach or trust (in any way) - then it returns 421 service not available (connection refused, too many connections) instead of letting you connect.

Please let me know if you'd have any more questions. Also — if the advice above works for you, then would you please go ahead and close the ticket?

Thanks

**Comment by luisfernandos** [comment]
Hi 

  Thanks for your response, a friend of mine told me that it didn't work for a localhost, perhaps a comment in your readme would help.


  Best regards,

  Fernando
  ----- Original Message -----

**Comment by kamilc** [comment]
Added the info about it in README. Thank you @luisfernandos for pointing this out.
